name: MomentsApp
options:
  bundleIdPrefix: com.moments
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.0"
  groupSortPosition: top

settings:
  SWIFT_VERSION: 5.9
  DEVELOPMENT_TEAM: "" # Will be filled by user

targets:
  MomentsApp:
    type: application
    platform: iOS
    sources:
      - path: MomentsApp
        excludes:
          - "**/.DS_Store"

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.moments.MomentsApp
      INFOPLIST_FILE: MomentsApp/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      TARGETED_DEVICE_FAMILY: "1,2"
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"
      ENABLE_PREVIEWS: YES
      SWIFT_EMIT_LOC_STRINGS: YES
      CODE_SIGN_STYLE: Automatic

    info:
      path: MomentsApp/Info.plist
      properties:
        CFBundleDisplayName: Moments
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: ""
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: false
        NSPhotoLibraryUsageDescription: "We need access to your photo library to select videos for creating highlights."
        NSPhotoLibraryAddUsageDescription: "We need access to save your video highlights to your photo library."
